Aeotec_TriSensor:
  name: Aeotec TriSensor
  control: hidden
  entities:
    - sensor.aeotec_zwa005_trisensor_alarm_level
    - sensor.aeotec_zwa005_trisensor_alarm_type
    - sensor.aeotec_zwa005_trisensor_burglar
    - sensor.aeotec_zwa005_trisensor_luminance
    - sensor.aeotec_zwa005_trisensor_sourcenodeid
    - sensor.aeotec_zwa005_trisensor_temperature
    - binary_sensor.aeotec_zwa005_trisensor_sensor